apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-belajar
  namespace : staging-test
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: hello-world
          image: putradocler/hello-world:v0
          env:
            - name: PORT
              value: "8080"
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 32Mi
