## Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-belajar
  namespace : staging-test
spec:
  selector:
    matchLabels:
      app: staging-belajar
  template:
    metadata:
      labels:
        app: staging-belajar
    spec:
      containers:
        - name: staging-belajar
          image: putradocler/hello-world:v10
          env:
            - name: PORT
              value: "8181"
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8181
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          envFrom:
            - configMapRef:
                name: staging-belajar

---
## Service
apiVersion: v1
kind: Service
metadata:
   name: staging-belajar
   namespace: staging-test
spec:
  type: ClusterIP
  selector:
    app: staging-belajar
  ports:
  - port: 8181
    name: http

--- # auto scaling pods 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: staging-belajar
  namespace: staging-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staging-belajar
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

--- # ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-belajar
  namespace: staging-test
data:
  APPLICATION: Hello World
  VERSION: 1.0.0

